spring:
  application:
    name: beam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:teambeam}
    username: ${DB_USER:your_db_user}
    password: ${DB_PASSWORD:your_db_password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:your_email@gmail.com}
    password: ${EMAIL_PASSWORD:your_email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

jwt:
  secret: ${JWT_SECRET:your_jwt_secret}
  refreshSecret: ${JWT_REFRESH_SECRET:your_refresh_secret}
  expiration: ${JWT_EXPIRATION:604800}  # 기본값 1주일
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800}  # 기본값 1주일

kakao:
  client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
  redirect-uri: ${KAKAO_REDIRECT_URI:https://example.com/user/login}

management:
  endpoints:
    web:
      exposure:
        include: "shutdown"
  endpoint:
    shutdown:
      enabled: true
